### ISSUE TITLE
Better pre-commit hook

### ISSUE THREAD

**Issue by jamesbraza** [trailofbits/pip-audit#334]
**Is your feature request related to a problem? Please describe.**

The current suggested pre-commit hook [here](https://github.com/trailofbits/pip-audit#pre-commit-support) will run on every commit.

```yaml
  - repo: https://github.com/trailofbits/pip-audit
    rev: v2.4.3
    hooks:
      -   id: pip-audit
          args: ["-r", "requirements.txt"]
```

Check the suggested hook for `pip-tools`: https://github.com/jazzband/pip-tools#version-control-integration

```yaml
  - repo: https://github.com/jazzband/pip-tools
    rev: 6.3.0
    hooks:
      - id: pip-compile
        files: ^requirements/production\.(in|txt)$
        args: [--index-url=https://example.com, requirements/production.in]
```

This runs only when the relevant files have changed.

**Describe the solution you'd like**

What do you think of updating the suggested pre-commit config to use a `files` filter?

That way, `pip-audit` is less invasive, and we cut down on CI compute costs. 🌎 

**Additional context**
